name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_WINDAFORT }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_WINDAFORT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build images
        run: docker-compose build

      - name: Push iekn-auto-rag image
        run: |
          docker tag iekn_auto-rag:latest ${{ secrets.DOCKER_HUB_USERNAME_WINDAFORT }}/iekn_auto-rag:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME_WINDAFORT }}/iekn_auto-rag:latest

      - name: Push Ollama image
        run: |
          docker tag iekn_ollama:latest ${{ secrets.DOCKER_HUB_USERNAME_WINDAFORT }}/iekn_ollama:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME_WINDAFORT }}/iekn_ollama:latest

      - name: Logout from DockerHub
        run: docker logout
