services:
  mgmt-service:
    build:
      context: modules/mgmt-service/
      dockerfile: Containerfile
    container_name: mgmt-service
    depends_on:
      - consul
  rag-service:
    build:
      context: modules/rag-service/
      dockerfile: Containerfile
    container_name: rag-service
    depends_on:
      - consul
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"