name: 00 - Main CI / CD Pipeline

on: 
  push:
    branches: [ "development" ]
    paths-ignore: 
    - '**/*.md'
    - '**/*.txt'
  pull_request:
    branches: [ "development" ]
    types: [opened, synchronize, reopened]
    paths-ignore: 
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing another stub-workflow!"