name: 01 - Run software and security tests

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  sast:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
        with:
          args: >
            -Dsonar.organization=nus-mtech-team-alpha
            -Dsonar.projectKey=nus-mtech-team-alpha_iekn
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml