name: 01 - Run software and security tests

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  sast:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: '17'
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
        # with:
        #   args: >
        #     -Dsonar.organization=nus-mtech-team-alpha
        #     -Dsonar.projectKey=SonarCloudCodeAnalysis
        #     -Dsonar.python.coverage.reportPaths=coverage.xml