# name: 03 - Deploy web app

# on: 
#   workflow_dispatch:
#   workflow_call:

# jobs:
#   deploy:
#     name: docker_build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0